AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Finance App FastAPI Backend

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        # These map the Parameters (below) to Python Environment Variables
        DB_USER: !Ref DbUser
        DB_PASSWORD: !Ref DbPassword
        DB_HOST: !Ref DbHost
        DB_PORT: !Ref DbPort
        DB_NAME: !Ref DbName
        SECRET_KEY: !Ref SecretKey
        AZURE_CLIENT_ID: !Ref AzureClientId
        AZURE_TENANT_ID: !Ref AzureTenantId
        ALGORITHM: !Ref Algorithm

Parameters:
  # These prompt you for values during 'sam deploy --guided'
  DbUser:
    Type: String
  DbPassword:
    Type: String
    NoEcho: true
  DbHost:
    Type: String
  DbPort:
    Type: String
    Default: "6543"
  DbName:
    Type: String
    Default: "postgres"
  SecretKey:
    Type: String
    NoEcho: true
  AzureClientId:
    Type: String
  AzureTenantId:
    Type: String
  Algorithm:
    Type: String
    Default: "HS256"

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.main.handler
      Runtime: python3.9
      Architectures:
        - arm64
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"